### ISSUE TITLE
When user switch between tabs,years at top right disappears.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#105]
**SEVERITY:**  Major

**MODULE:** 
•	Bar Rank

**STEPS TO REPRODUCE:**
1.Open offline Application.
2.Open Bar rank  and open 2-3 other chart in new tab before the first one loads.
3.Switch back to first tab.

**ACTUAL RESULTS:**
When user switch between tabs,years at top right disappears.

**EXPECTED RESULTS:**
When user switch between tabs,years at top right shouldn't disappear.

**SCREENSHOT:**
![v3](https://user-images.githubusercontent.com/9950837/28210524-42056b7c-68b1-11e7-948b-3a45f39ad96a.png)

![v4](https://user-images.githubusercontent.com/9950837/28210642-d81d98be-68b1-11e7-918e-bac6abaab613.png)

**Comment by buchslava** [comment]
@kuguarpwnz The reason depends on vizabi, not on gapminder-offline particular, I suppose. I suspect this style of code (this code is adapted only for one instance of this kind of chart):
![screenshot from 2017-07-24 18-31-37](https://user-images.githubusercontent.com/6974213/28531826-9f20ae2e-70a0-11e7-885c-239b69c124f9.png)

what do you think?

**Comment by kuguarpwnz** [comment]
duplication https://github.com/Gapminder/gapminder-offline/issues/82

**Comment by kuguarpwnz** [comment]
@buchslava yes, you're right. fixed here https://github.com/vizabi/vizabi-barrankchart/commit/f47ab6d9d05f94b063c9091e67b4d3e80ddc94d3

**Comment by buchslava** [comment]
@kuguarpwnz please publish vizabi/vizabi-barrankchart
