### ISSUE TITLE
When user click on Version number,404 Error occurred.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#106]
**SEVERITY:**  Major

**MODULE:** 
•	All Charts

**STEPS TO REPRODUCE:**
1.Open offline Application.
2.Open any chart.
3.Click on "Options" at bottom right
4.Click on "About"
5.Click on Version number.

**ACTUAL RESULTS:**
When user click on Version number,404 Error occurred.

**EXPECTED RESULTS:**
When user click on Version number,404 Error shouldn't  occur.

**SCREENSHOT:**

![v5 b](https://user-images.githubusercontent.com/9950837/28211474-45e8e0c0-68b6-11e7-9ff0-1535768c6bb1.png)
![v5](https://user-images.githubusercontent.com/9950837/28211476-46068e36-68b6-11e7-81d0-074ab5218283.png)

**Comment by buchslava** [comment]
@k6Labz it's not an issue of gapminder-offline, this is vizabi's issue

@angieskazka @jheeffer

**Comment by buchslava** [comment]
apart from that I recommend 'target="_blank"' in this case:

<a href="https://github.com/Gapminder/vizabi/releases/tag/v0.25.0-2" target="_blank">Version: 0.25.0-2</a>
