### ISSUE TITLE
Feature: Add time format selector

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#112]
The most frequent user request is to be able to display data where time points are not years but some other units: months, days, weeks, quarters

Let's add a section where we can select time format (year being a default)

![image](https://user-images.githubusercontent.com/3648190/30373173-acbf6bf8-9880-11e7-8bcb-6fa6e193a132.png)

this is a quick and ugly sketch but i believe you can make it look nice, like the rest of the panel

"year" is default and adds nothing to the config of a new tool:

"month" is the other option and it adds this to the config of a new tool:

```
state: {
    time: {
      unit: "month",
      format: {
        data: "%Y-%m",
        ui: "%B %Y"
      }
    }
 }
```

test using this file: 
https://github.com/vizabi/vizabi-preview/blob/master/src/data/waffles/basic-indicators-month.csv

for the "Add data to the existing chart" add the following:

check the state of the existing chart, the value in state: time: unit

and then use it to pre-select the item in dropdown and change example text

then disable dropdown, so that it's visible that time points can only be what was selected at first in the chart

**Comment by buchslava** [comment]
@angieskazka tell me please what should I see in Vizabi in case of `month`?
