### ISSUE TITLE
Different installer icon to avoid confusion with the icon of the actual app installed

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#115]
Can we make the downloaded installer use a different icon, it ends up hanging in my Desktop and I click it and se the “drag to Applicaiotns folder” but it looks like the software… Add a mino Icon for “installer” somehow on top of the yellow G

![image](https://user-images.githubusercontent.com/3648190/30452347-a490314a-9995-11e7-9926-1737802f4ba3.png)

**Comment by buchslava** [comment]
@angieskazka what kind of icon do you prefer?

**Comment by angieskazka** [comment]
@buchslava i've added some icons here 
https://github.com/Gapminder/gapminder-offline/commit/df3749f27d53572420b176a15650f9ca55f20c44
