### ISSUE TITLE
32bit version: Opacity control slider doesn't work

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#123]
Steps to reproduce:
1. Open any chart (e.g. bubble);
2. Click on any bubble
3. Drag opacity control slider to any position
Now it became insensitive to any changes.

![selection_048](https://user-images.githubusercontent.com/18219232/30642008-bc427818-9e11-11e7-96bf-9c6a4061de48.png)

**Comment by angieskazka** [comment]
reproduced on gapminder offline and on tools page, but not on preview page. weird.

**Comment by angieskazka** [comment]
looks fixed to me (parallels Win10 x64, App v3.0.0 x32)
