### ISSUE TITLE
Bug: broke the app by opening a file twice in one chart

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#125]
open bubble chart
add data - csv file - pick a csv
select the imported data for Y axis
modify the file, for example, change indicator name
add data - csv file - pick the same csv

might be a vizabi issue

**Comment by angieskazka** [comment]
now the app doesn't crash but the data doesn't update either

**Comment by angieskazka** [comment]
for example, if the first time the file contained indicator POP and the second time it was renamed to POPULATION, only POP shows up in UI, and console complains that there is no such indicator in the concept dictionary

**Comment by dab2000** [comment]
looks like not vizabi issue,
vizabi got updated model with non changed 'lastModified' for csv file.
need check 'additionalItems' directive in 'ng2-vizabi' or 'additional-data' component in 'gapminder-ofline'

**Comment by angieskazka** [comment]
checked now, still persists

**Comment by sergeyKhristenko** [comment]
For now, after uploading the same file(with some changes) again - the changes will appear in the UI. The old indicators won't be available.
