### ISSUE TITLE
Sometimes error message while parse CSV not shown and new chart can't be opened

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#131]
In this case, the page will spin forever and any chart won't be opened even in a new tab.
Steps:
1. Open bubble chart (or any other)
2. Add data to chart (use CSV file from attachment) (choose 'Times goes right')
3. In the filter above the minimap choose your CSV->POP (please see attached screenshot)
Proper error appers
4. Open new tab and repeat the same steps
Now any chart can't be opened - just infinite spinner. Please see screenshot

It always happened when the same error duplicated in another tab. Also, I've tried two identical CSV files placed in different folders (to exclude any caching related issues) - the result was the same.

screenshot with settings:
![selection_059](https://user-images.githubusercontent.com/18219232/30687883-405d796e-9ec5-11e7-8eae-651ad5e26c58.png)

test file:
[basic-indicators.csv.zip](https://github.com/Gapminder/gapminder-offline/files/1320573/basic-indicators.csv.zip)

screenshot with the error:
![selection_058](https://user-images.githubusercontent.com/18219232/30687974-9270f29e-9ec5-11e7-9f93-b7a4b82e43fc.png)

**Comment by angieskazka** [comment]
this is my error if i pick "time goes right"

![image](https://user-images.githubusercontent.com/3648190/31999297-1023d872-b993-11e7-8621-9de802e91128.png)


if i choose "time goes down" it works

![image](https://user-images.githubusercontent.com/3648190/31999392-5b6c1452-b993-11e7-8999-6684c762fcef.png)

and was able to do it second time too

![image](https://user-images.githubusercontent.com/3648190/31999436-7dcf1134-b993-11e7-85dd-0f256ac56296.png)

**Comment by angieskazka** [comment]
retested on mac and windows: works fine

**Comment by sergeyKhristenko** [comment]
I have error when choose 'time goes right'
![selection_250](https://user-images.githubusercontent.com/18219232/32108317-fe2fdf32-bb39-11e7-8abe-22536a32b820.png)

and no errors when choose 'time goes down'

movie:
![ezgif com-video-to-gif 16](https://user-images.githubusercontent.com/18219232/32108324-08958d1e-bb3a-11e7-8a6c-2997c6e53133.gif)
