### ISSUE TITLE
"Create new chart from Gapminder data" doesn't work properly for the first time

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#132]
The issue reproduces just after the start when no charts were created. After adding any shart the issue is not reproduced.

Steps:
1. Open app
2. File -> New chart -> Gapminder data
Please see attachment

![chartfromdata](https://user-images.githubusercontent.com/18219232/30706975-b5014128-9f02-11e7-8169-6db8525ee93f.gif)

**Comment by angieskazka** [comment]
Expected: a new tab would be added
