### ISSUE TITLE
Allow to "Add data to the active chart" only on active chart

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#136]
Sometimes this menu appears without actually opened chart on the tab
Steps to reproduce:
1. Open app
2. Add new tab
3. Choose any chart on this second tab
4. Go back to the first tab (without any chart on it)
5. File -> Add data to the active chart  - all the options should be disabled

![selection_074](https://user-images.githubusercontent.com/18219232/30742079-3d14a6d4-9fa0-11e7-9016-5d77907e9fc6.png)

**Comment by angieskazka** [comment]
Expected: option "Add data..." is disabled when looking at the tab with no chart open
