### ISSUE TITLE
Text is missing and additional names been added 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#146]
**SEVERITY:** Minor

**MODULE:**
• All Charts 

**STEPS TO REPRODUCE:**
1. Hit URL http://tools-stage.gapminderdev.org
2. Select the population against 'Size' field
3. Observe the issue by see the screenshot

**ACTUAL RESULTS:**
Text is missing and additional names been added 
1.	‘Population, total’ is being added in the offline app instead of ‘population’
2.	Unit for population is not mentioned
3.	‘CO2 emission’ is being added instead of ‘CO2 per capita’ 

**EXPECTED RESULTS:**
1.	‘Population, total’ should be replaced in the offline app with ‘population’
2.	Unit for population should be mentioned as it is online app	
3.	‘CO2 emission’ should be replaced with ‘CO2 per capita’ 

**SCREENSHOT:**
![12](https://user-images.githubusercontent.com/9950837/30860959-977b59fc-a2e2-11e7-9790-df987d6e54c0.png)

**Comment by angieskazka** [comment]
@k6Labz duuude, that's vizabi too

**Comment by angieskazka** [comment]
these are improvements of a more human-readable names in the new version of a dataset
