### ISSUE TITLE
Indicators not available on X/Y-axis

### ISSUE THREAD

**Issue by aksel92** [Gapminder/gapminder-offline#149]
one of the indicatiors in my datachart is available to change size, but not in the X/Y axis, is there a particular format needed to make them available on the axis?

**Comment by angieskazka** [comment]
could be possibly that it was interpreted as text because you have a weird symbol somewhere among the values. if you want empty cells you should have them empty, not anything like ".." or "-"

**Comment by angieskazka** [comment]
if you can show the data i can tell more @aksel92
