### ISSUE TITLE
Export for web missing js files

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#157]
windows10 x64

app v2.2.1
start gapminder offline 
open a csv file (the one i used you can find it in the attached zip/data)
everything works ok
press save to web
the resulting zip is missing all JS files

![image](https://user-images.githubusercontent.com/3648190/31551215-280bcebc-b034-11e7-9342-4b5cde89852f.png)
[test.zip](https://github.com/Gapminder/gapminder-offline/files/1382906/test.zip)

**Comment by buchslava** [comment]
@angieskazka this issue was resolved from 2.2.2 that's why I recommend update 2.2.1 to 2.2.2

**Comment by angieskazka** [comment]
@buchslava still doesn't work on windows on v2.3.0
