### ISSUE TITLE
Wrong working directory when opening g offline via gmstat

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#159]
windows 10 x64

Open G offline from a gmstat file, press update, directory "cache" is being created there next to the user's gmstat file

**Comment by buchslava** [comment]
@angieskazka I guess we should prevent any gmstat based action during updating. am I right?

**Comment by angieskazka** [comment]
1. open gmstat
2. app opens, update is suggested
3. press update
4. app creates "cache" folder next to gmstat, but
it should create "cache" where it's installed

**Comment by buchslava** [comment]
@angieskazka ok, understand, thanks

**Comment by sergeyKhristenko** [comment]
Steps:
1. Open GOffline through gmstat file
2. Press Autoupdate
Error: Can not find script file "../invisible.vbs"

![selection_044](https://user-images.githubusercontent.com/18219232/33376335-f517498a-d515-11e7-92ba-c906f466d0a0.png)

**Comment by angieskazka** [comment]
still persists, yes

![image](https://user-images.githubusercontent.com/3648190/33558962-024505aa-d914-11e7-8eff-f247dd9c90ce.png)
