### ISSUE TITLE
Check git label before updating dataset and don't crash if it's missing

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#162]
ideally don't even show the update suggestion

**Comment by buchslava** [comment]
@angieskazka What do you mean (label)? I it regarding tag? Please provide more information regarding the issue.

**Comment by angieskazka** [comment]
@buchslava yes, sorry, tag
i merged a dataset into master but didn't put a tag on it because i didn't want offline app to autoupdate yet. instead it wanted to autoupdate and broke :)

**Comment by buchslava** [comment]
@angieskazka sorry, still unclear

Autoupdater has only one criterion for starting. This is 'vresion' field in datapackage.json. If we changed it autoupdater would be started, .... or no if version field was not changed. We haven't any other relation in github for autoupdater functionality that will be useful for update process starting. That's why I don't understand what should I do...

**Comment by buchslava** [comment]
@angieskazka aha, I guess, I understand: as far as I see version in datapackage is greater than version in tag. I can propose next logic: in any case we should use version field in datapackage as autoupdate criterion. But I can provide functionality when autoupdater will be started only during major on minor DS change, not patch change. Apart from that manual DS updating should be provided in this case. What do you think?

**Comment by angieskazka** [comment]
my problem was that autoupdate crashed because there was no tag on git attached to the new version. can it not?

@angie I can't understand how github tag related to autoupdate

so, maybe that’s one thing to research
i can replicate but don’t want to do it on a live version

@angie please provide me steps to reproduce; by the way, gapminder-offline has `au-test` mode that's why I may reproduce this issue on non-production

download g offline with dataset 1.2.2 (gapminder.org/tools-offline)
bump version of the dataset 1.2.3
merge dataset to master
local g offline wants to update, press ok
it crashes

now add a tag on github `v1.2.3`
reopen g offline, it suggests to update
press update
update goes as expected

apart from that: don’t start autoupdate on patch change (edited)
sounds reasonable
