### ISSUE TITLE
Clear input after upload a file

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#169]
Or maybe it would be nice to add styles for disabled buttons.

![selection_241](https://user-images.githubusercontent.com/18219232/32055145-9ad1bcb0-ba69-11e7-859f-369abb1f5e24.png)

Steps to reproduce:
1. Create new chart from csv file
2. Click on "Create new chart from csv file" again

It seems like all fields are filled but 'Ok' button disabled. It's a bit confusing

**Comment by angieskazka** [comment]
forwarding to #167
