### ISSUE TITLE
New line chart from user data starts from the start

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#170]
Our "standard" line chart opens with drawn lines but when Line chart created on users data it opens with just a dot on the left side of the chart.

![selection_240](https://user-images.githubusercontent.com/18219232/32055422-718fc210-ba6a-11e7-99c0-58515b39838c.png)

**Comment by angieskazka** [comment]
this is expected, someone requested this to be able to start the graph and press play before unveiling the complete story

**Comment by angieskazka** [comment]
our chart is configured in a special way
