### ISSUE TITLE
In v.2.3.0 chart created from CSV is different than in v.2.2.2

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#176]
![selection_246](https://user-images.githubusercontent.com/18219232/32062869-68f77b48-ba7e-11e7-8ae9-d97a3833a857.png)

[basic-indicators.csv.zip](https://github.com/Gapminder/gapminder-offline/files/1419073/basic-indicators.csv.zip)

**Comment by angieskazka** [comment]
@sergeyKhristenko  that's alright, there are updates in vizabi autoconfig
