### ISSUE TITLE
Styles for 'update dataset'

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#182]
![selection_252](https://user-images.githubusercontent.com/18219232/32113392-db765610-bb48-11e7-97e5-4613cae3a432.png)

![selection_253](https://user-images.githubusercontent.com/18219232/32113403-e4b465dc-bb48-11e7-95b7-bfaf176a452c.png)

**Comment by buchslava** [comment]
@sergeyKhristenko I think it should be fixed on 3.0.0

**Comment by angieskazka** [comment]
win32 version:

now it says "new dataset is available"

**Comment by buchslava** [comment]
this issue was not reproduced under 3.0.0

**Comment by sergeyKhristenko** [comment]
We should show separate messages for Update dataset and Update app
