### ISSUE TITLE
Is there a way for us to attach gapminder graph into Powerpoint?  Thanks.

### ISSUE THREAD

**Issue by Mamalai** [Gapminder/gapminder-offline#183]

**Comment by jheeffer** [comment]
Hi Mamalai. 

We recommend either: 

1. Make a slide with a screenshot of the graph and switch to gapminder offline when you reach the slide.

or 

2. Take video using screen capturing software (for example: https://icecreamapps.com/Screen-Recorder/) and put that into your presentation.

Which one you choose depends on your use case. For example how interactive/unscripted you want your presentation to be ; )

**Comment by Mamalai** [comment]
Thank you for the suggestion. I used the 2nd choice and it worked!  Appreciate for your advice.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
