### ISSUE TITLE
"Options" windows disappeared before clicking "Ok" button while time is playing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#184]
SEVERITY: Minor

MODULE:
• All Charts

PLATFORM:
• Windows 10

STEPS TO REPRODUCE:
1. Open the offline Gap Application
2) Click on Options at bottom right
3)Click on Size
4)Change the size.

ACTUAL RESULTS:
Options window disappeared before clicking OIK button. 

EXPECTED RESULTS:
Windows should disappear after user click OK button.

SCREENSHOT:
http://g.recordit.co/7mpHuFK2xQ.gif

**Comment by angieskazka** [comment]
seems to be fixed in 3.0.0
