### ISSUE TITLE
All Charts | User is able to change the Size/Opacity/ Speed of bubbles without selecting respective slider. 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#185]
SEVERITY: Major

MODULE:
1) Bubble Map
2) Bubble chart

PLATFORM:
• Windows 10

STEPS TO REPRODUCE:

1)Open the offline Gap Application
2)Click on Options at bottom right
3)Click on Size
4)Change the size 
5)As options windows disappear,long press the mouse button and move the cursor in same direction as moved for changing size. 

ACTUAL RESULTS:
User is able to change the Size/Opacity/ Speed of bubbles without selecting respective slider. 

EXPECTED RESULTS:
User should not  able to change the Size/Opacity/ Speed of bubbles without selecting respective slider. 

SCREENSHOT:
http://g.recordit.co/Li2lU09Wx7.gif

**Comment by angieskazka** [comment]
seems to be fixed in 3.0.0
