### ISSUE TITLE
User is unable to Drag and drop the "Options" dialog on large screen.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#186]
SEVERITY: Major

MODULE:
All charts

PLATFORM:
• Windows 10

STEPS TO REPRODUCE:

1)Open the offline Gap Application
2)Click on Options at bottom right
3)Drag dialog and drop on large window.

ACTUAL RESULTS:
Options Dialog disappeared as user dropped it on large screen.

EXPECTED RESULTS:
Options dialog should not disappear.

SCREENSHOT:
http://g.recordit.co/Rj5iPTPy4a.gif

**Comment by angieskazka** [comment]
seems to be fixed in 3.0.0
