### ISSUE TITLE
Double error when no datapackage.json in DDF folder

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#188]
There is a popup with error and then just blank page with an error. If we already show error, then why to show a page with the error? I suggest there should be either default page or dialog to select DDF folder.

Steps to reproduce:
1. Click on hamburger menu
2. New chart -> Your data -> DDF Folder
3. Select any folder without datapackage.json

![selection_034](https://user-images.githubusercontent.com/18219232/33264689-4dfe2938-d377-11e7-9bf0-be33a77831c3.png)

**Comment by angieskazka** [comment]
don't allow opening a DDF folder when there is no datapackage.json present
