### ISSUE TITLE
Windows 10 | Offline App | All Charts | Slider ball is missing on all charts

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#197]
STEPS TO REPRODUCE:**
1. After downloading the latest offline app v3.0.0, open it
2 .Open any chart and play it.

**ACTUAL RESULTS:**
Slider ball is missing on all charts

**EXPECTED RESULTS:**
Slider ball should not be missed on all charts

**SCREENSHOT:**
![17](https://user-images.githubusercontent.com/9950837/33596330-27c795dc-d9bd-11e7-8767-47f2c371a2f9.png)

**Comment by sergeyKhristenko** [comment]
Can't reproduce. Maybe there are some specific steps? 
What is the version of the app - 32 or 64?

**Comment by angieskazka** [comment]
@k6Labz and what windows is it running on?

**Comment by k6Labz** [comment]
@angieskazka It happens when you try to open all charts simultaneously one by one on different tabs, then play it on last chart i.e. 'Line' chart.
