### ISSUE TITLE
Windows 10 | Offline App | 'Rankings' Chart | User is unable to scroll down to see the selected countries in specific region

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#198]
**STEPS TO REPRODUCE:**
1. After downloading the latest build v3.0.0, open it.
2. Open 'Rankings' chart 
3. Select 'select all in that group' by hovering the mouse to any specific region in mini map
4. Observe the issue by scrolling down the page to see the issue.

**ACTUAL RESULTS:**
User is unable to scroll down to see the selected countries in specific region

**EXPECTED RESULTS:**
User should be able to scroll down to see the selected countries in specific region

**SCREENSHOT:**
![18](https://user-images.githubusercontent.com/9950837/33596810-f45539d2-d9be-11e7-8732-2ccf5ed6675d.png)

**Comment by angieskazka** [comment]
Looks like it was fixed together with #197
