### ISSUE TITLE
Lack of colors in the list in sidebar

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/gapminder-offline#207]
I'm not sure that it comes from the latest version

![selection_065](https://user-images.githubusercontent.com/18219232/33775359-c91d2498-dc46-11e7-9250-8e864d2abf3d.png)

![selection_066](https://user-images.githubusercontent.com/18219232/33775365-cd2397b6-dc46-11e7-8b47-ab24a2d7f3c0.png)

**Comment by angieskazka** [comment]
turns out this was a reader issue and it's fixed in DDFCSV reader 2.0.2
