### ISSUE TITLE
Add support for copy and paste

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#212]
both in the app and in dev tools

see this
https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by buchslava** [comment]
@angieskazka explain me please, what data should be copied and pasted?

**Comment by angieskazka** [comment]
@buchslava  all data... the regular copy and paste feature...

tab names
vizabi error messages (which we ask to copy but that's not possible)
content of the input fields, like, axis min max

in dev tools:
console errors
typing the code in console
source code pieces

**Comment by angieskazka** [comment]
update: and Ctrl+A too

**Comment by buchslava** [comment]
@angieskazka as far as I see Ctrl+C - Ctrl+V works well (at least in Linux). I'm not sure that I understand what the task means

**Comment by angieskazka** [comment]
this helped
