### ISSUE TITLE
Renaming tabs bug that removes some symbols while typing

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#214]
v 3.0.0
macOS EL capitan

Open G offline
open bubble chart
open map
open line chart
switch to bubble chart
attempt to rename the tab to "wealth and health"
see characters disappearing (every other symbol)

http://g.recordit.co/F4GdQIlyQW.gif
![f4gdqilyqw](https://user-images.githubusercontent.com/3648190/34412616-981fa544-ebde-11e7-885b-0537847623ef.gif)

@sergeyKhristenko please include this into acceptance test list for gapminder offline (let's create one!)

**Comment by sergeyKhristenko** [comment]
It happens when tab name is editing while the chart is loading.

Steps:
1. Open bubble chart
2. Edit the tab name while it is loading
