### ISSUE TITLE
Feature: Gapminder offline check modified date of opened files and reload if modified DYNAMICALLY

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#216]

**Comment by buchslava** [comment]
@angieskazka tell me please what behavior regarding Vizabi model during DS changes should be provided:

1. reload all of the charts immediately without any asking
2. reload all of the charts after asking "Dataset was changed. Reload it? Yes-No" and after that try to restore all of the previous chart settings (model)
3. reload all of the charts after asking "Dataset was changed. Reload it? Yes-No" and after that, DON'T try to restore all of the previous chart settings (minimal default model)

PS: I guess, reload all of the charts immediately without any asking and restore the previous state is not a good solution

**Comment by angieskazka** [comment]
Check modified time of each data source for files (in case of CSV) and folders (in case of DDF)
Do that on app focus for the active tab only and on tab switch for the target tab only
Yes, a message with reload Yes-no is a good idea. 
Only reload the active chart/tab
