### ISSUE TITLE
all of the charts are merged during SVG/PNG export

### ISSUE THREAD

**Issue by buchslava** [Gapminder/gapminder-offline#223]
1. create many charts
2. export to png

expected behavior: only current chart from the current tab should be exported

![image](https://user-images.githubusercontent.com/3648190/34414535-1a141444-ebea-11e7-98d1-91322f11fb9e.png)

**Comment by sergeyKhristenko** [comment]
related to: https://github.com/Gapminder/gapminder-offline/issues/209
