### ISSUE TITLE
When user click on specific region of mini map the bubbles related to that region did not appeared 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#25]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart 

**PLATFORM:** 
* Bubble Chart (Offline)

**STEPS TO REPRODUCE:**
1) Open the offline Gap minder page 
2) Click on any region from mini map  

**ACTUAL RESULTS:**
When user click on specific region of mini map the bubbles related to that region did not highlighted with their labels 

**EXPECTED RESULTS:**
The bubbles should be highlighted with their labels

**Comment by vvpanchenko** [comment]
Looks like issue with Reader

**Comment by Legionivo** [comment]
Not actual anymore
