### ISSUE TITLE
On opening & closing of chart's TAB, TAB's number should updated accordingly.

### ISSUE THREAD

**Issue by abidrana7** [Gapminder/gapminder-offline#255]
**AUT:** Offline App v3.4.0 (dataset v1.7.2)
**CHARTS:** All

**STEPS TO REPRODUCE:**
1. Click on "+" up to 8 times (or how many times you want to)
2. Open any chart whichever you want in each opened TAB.
3. Close any of the opened charts randomly i.e. at number 3, 4, 6 etc.
4. Note that remaining Open charts will still shows there TAB's number, instead of updating the them.

**ACTUAL RESULTS:** On opening & closing of chart's TAB, numbers appear randomly.
**EXPECTED RESULTS:** On opening & closing of chart's TAB, TAB's number should updated accordingly.

![numbers appear randomly](https://user-images.githubusercontent.com/16793789/46569375-8e405880-c96d-11e8-970c-2992a9933cef.png)

**Comment by buchslava** [comment]
@angieskazka @abidrana7 is it an issue? `TAB's number should updated accordingly` has very tricky functionality, is it needed? one more point: we can rename any tab at any moment (double-click on the tab title). that's why, I think, strict tab numbers are not valuable.

**Comment by buchslava** [comment]
@abidrana7 
apart from that unordered tab numbers is normal practice for Google, for example
![screenshot from 2018-10-08 11-33-09](https://user-images.githubusercontent.com/6974213/46598858-472da100-caee-11e8-9303-98c762ae8164.png)

**Comment by angieskazka** [comment]
this works as intended :)

**Comment by abidrana7** [comment]
@buchslava
you gave awesome Google's sheet example, indeed impressive one :)
