### ISSUE TITLE
after updating the offline app, unable to open the app through "Gapminder Offline.exe"

### ISSUE THREAD

**Issue by abidrana7** [Gapminder/gapminder-offline#259]
**AUT:** Offline App v3.4.0 (dataset v1.9.0)

**STEPS TO REPRODUCE:**
1. Update the app through the available updater option.
2. After waiting for few minutes, a message is appear then click on OK. 
3. Updated app won't started by itself. instead a blank page was appeared.
4. Start the app by clicking the "Gapminder Offline.exe".
5. Note that there's nothing happen.

**Comment by buchslava** [comment]
I just passed all of the steps:
![screenshot from 2018-10-08 12-16-00](https://user-images.githubusercontent.com/6974213/46605618-d1800000-cb02-11e8-967a-bb1cb664aace.png)
![screenshot from 2018-10-08 12-16-35](https://user-images.githubusercontent.com/6974213/46605623-d5138700-cb02-11e8-9c00-8597cc3f3c42.png)
![screenshot from 2018-10-08 12-18-20](https://user-images.githubusercontent.com/6974213/46605625-d80e7780-cb02-11e8-9d0e-240d3bdc80b1.png)
![screenshot from 2018-10-08 12-19-31](https://user-images.githubusercontent.com/6974213/46605628-db096800-cb02-11e8-8ef1-3fb16bce75d4.png)
and I don't see the issue, as for now, at least
looks unstable...
@abidrana7 @angieskazka

**Comment by buchslava** [comment]
ps: it was win10x64
apart from that, I passed the same flow on win7x32 and they were passed too

**Comment by abidrana7** [comment]
@buchslava 
yes, issue was on win10x64. Its fine and good to close this issue if its not reproducible at your end.

-updater option will only be available if there's actually updates available, right?
-see below screenshot, there is no updater option displayed coz in my case dataset is already updated to v1.13.0

**Comment by abidrana7** [comment]
Successfully done with updates from v3.5.0 to v4.0.0
