### ISSUE TITLE
When user click on specific region of mini map the bubbles related to that region did not appeared 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#26]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart 

**PLATFORM:** 
* Bubble Chart (Offline)

**STEPS TO REPRODUCE:**
1) Open the offline Gap minder page 
2) Click on any region from mini map  
3) Hover on bubbles of that region which you selected 

**ACTUAL RESULTS:**
The labels of bubbles appeared on the corner of the chart 

**EXPECTED RESULTS:**
The labels should appear over the bubble

**SCREENSHOT:**
![1-5-2017 12-38-31 pm](https://cloud.githubusercontent.com/assets/9950837/21672489/bd50632a-d344-11e6-99ea-1efd1b2df329.jpg)

**Comment by vvpanchenko** [comment]
Looks like issue with Reader
