### ISSUE TITLE
The bubble disappeared from the chart 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#27]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart (Offline)

**PLATFORM:** 
* Win 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1) Open the offline Gap minder page 
2) Double click on any region from mini map e.g. America
3) Now double click on Asia region from mini map
4) Now double click on Asia region again 

**ACTUAL RESULTS:**
The bubble disappeared from the chart 

**EXPECTED RESULTS:**
The bubble should not disappear from the chart 

**SCREENSHOT:**

![1-5-2017 3-36-00 pm](https://cloud.githubusercontent.com/assets/9950837/21677602/b16914cc-d35c-11e6-850a-171e78023bf4.jpg)

**Comment by vvpanchenko** [comment]
Investigate a bit. Looks like csv-reader returns an empty result when more then one region selected (section: `join`, in level: `$in`: [...])

**Console**: Reader for data source 'data' returned empty array for query
**Query**: {
  "language": "en",
  "from": "datapoints",
  "animatable": "time",
  "select": {
    "key": [
      "geo",
      "time"
    ],
    "value": [
      "population_total"
    ]
  },
  "where": {
    "$and": [
      {
        "geo": "$geo"
      }
    ]
  },
  "join": {
    "$geo": {
      "key": "geo",
      "where": {
        "world_4region": {
          "$in": [
            "americas",
            "asia"
          ]
        }
      }
    }
  },
  "order_by": [
    "time"
  ]
}
