### ISSUE TITLE
The application crashes when user zoom in the app 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#34]
**Steps To Reproduce:**
1. Launch the application 
2. Click on bubble chart 
3. Click on options
4. Click on zoom 
5. Click on zoom with mouse wheel check box 
6. Now zoom in to maximum 

**ACTUAL RESULT:**
The application crashes and user have to re launch the application 

**EXPECTED RESULT:**
The application should not crash or stuck 

![1-17-2017 12-51-29 pm](https://cloud.githubusercontent.com/assets/9950837/22012021/d7c8e7d6-dcb3-11e6-897b-a03d4f4720d4.jpg)

**Comment by Legionivo** [comment]
Not actual anymore
