### ISSUE TITLE
Alignment issue of text in mountain chart.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#48]
**SEVERITY:**  Minor

**MODULE:** 
	• Mountain chart.

**PLATFORM:** 
	 • Windows10 

**STEPS TO REPRODUCE:**
     1. Open the offline Gap minder page
     2.Click on Mountain chart.
     3.Click on “Options” at bottom right.
     4. Click on “Stack”.

**ACTUAL RESULTS:**
Text isn’t properly aligned.

**EXPECTED RESULTS:**
Text should be aligned properly.

**SCREENSHOT:**
![off1](https://cloud.githubusercontent.com/assets/9950837/23653772/7cc419f0-02e2-11e7-9f82-69119e52a08e.jpg)

**Comment by Legionivo** [comment]
Present on Linux too

**Comment by k6Labz** [comment]
Issue still persist

**Comment by angieskazka** [comment]
still an issue @dab2000 :(
but now slightly different

http://g.recordit.co/wOchJvh85R.gif

![wochjvh85r](https://user-images.githubusercontent.com/3648190/32910189-dc5cbdd8-cb08-11e7-876f-f179a4c72867.gif)

![image](https://user-images.githubusercontent.com/3648190/32910247-02d98cb6-cb09-11e7-80c3-0f4378ec2f49.png)

**Comment by dab2000** [comment]
fixed vizabi/vizabi@67b8970
