### ISSUE TITLE
files are cached under their names, this is bad

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#51]
1. open a broken csv file in vizabi
2. vizabi complains it's broken
3. fix the file, save it
4. open again
5. vizabi complains it's broken
6. restart the app
7. open the file, now it's good!

this is because the file is cached under its name, and the broken info is stuck in gapminder offline
this is also why you can't open same CSV file twice

**Comment by jheeffer** [comment]
@angieskazka did you test if it's file name or file path? I.e. same file name in a different path is also same cache?

Anyway, caching should happen on file path and look at the modified timestamp of the file, yes.

**Comment by buchslava** [comment]
@angieskazka this issue is not depending on GA or ng2-vizabi; the reason is in vizabi, please comment next `if`: https://github.com/vizabi/vizabi/blob/develop/src/base/datastorage.js#L35

**Comment by sergeyKhristenko** [comment]
Looks like the same issue but with slightly different steps to reproduce.
Steps:
1. Open valid csv but choose incorrect  time value (year, monthly, etc.)
2. Open the same csv with correct time value;

And the same flow could be reproduced vice versa:
1. open csv with valid settings
2. open csv with invalid settings
Now the file will be opened with incorrect data on chart

**Comment by angieskazka** [comment]
this got fixed now
