### ISSUE TITLE
Error happens when 3 charts opened one by one

### ISSUE THREAD

**Issue by Legionivo** [Gapminder/gapminder-offline#53]
**Steps:**
1. Open offline app on Linux
2. Open 3 different charts one by one

**Actual result:** 
error displayed in console: 
`Error: <rect> attribute width: A negative value is not valid. ("-1.69")`

**Expected result:** 
no errors should be displayed

**Comment by angieskazka** [comment]
this is a vizabi bug: i moved it to https://github.com/vizabi/vizabi/issues/2570
