### ISSUE TITLE
Color panel doesn't open in its respective tab.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#58]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble chart

**STEPS TO REPRODUCE:**
1.Open offline application.
2.Open Bubble chart.
3.Select 3-4 countries and generate trails.
4.Open bubble map in new tab.
5.Switch back to first tab (Bubble chart) ,click on "Options" and change color indicator to "Life Expectancy"
6.Click on color scale to change color.

**ACTUAL RESULTS:**
Color panel doesn't open in its respective tab and opens in second tab(Bubble map)

**EXPECTED RESULTS:**
Color panel should open in its respective tab.

**SCREENSHOT:**

![off3](https://cloud.githubusercontent.com/assets/9950837/24185407/dd20b20e-0ef4-11e7-9768-dda285fd82a4.jpg)

**Comment by kuguarpwnz** [comment]
Less steps to reproduce:
1. Open bubble chart (Tab 1)
2. Open any other chart (Tab 2)
3. Switch back to Tab 1, click on "Options" and change color indicator to "Life Expectancy"
4. Click on color scale to change color.

**Comment by Legionivo** [comment]
Verified - fixed.
