### ISSUE TITLE
Missing bubbles on Bubble chart

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#80]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart.

**STEPS TO REPRODUCE:**
1.Open offline application.
2.Open Bubble Chart.
3.Open any other chart in new tab.(Open second chart before first chart loads completely)
4.Switch back to first tab (Bubble chart)

**ACTUAL RESULTS:**
Bubbles are missing on Bubble chart.

**EXPECTED RESULTS:**
Bubbles should be present on Bubble chart.

**SCREEN SHOT:**
![a1](https://cloud.githubusercontent.com/assets/9950837/24738455/542765ee-1aaf-11e7-9bcd-caaf5fadfc16.png)

**Comment by Legionivo** [comment]
Bubbles appear, but in a few seconds.

**Comment by Legionivo** [comment]
Verified - fixed
