### ISSUE TITLE
The size of Color panel in offline application is different from Color panel in Staging/Dev.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#81]
**SEVERITY:**  Minor

**MODULE:** 
•	All charts.

**STEPS TO REPRODUCE:**
1.Open offline Application
2.Open Bubble chart in 4 different tabs.
3.Switch between tabs.
4.Play slider on any tab (2nd tab).
5.Change color indicator to "CO2 per capita"(2nd tab).
6.Click on color scale and change color.

**ACTUAL RESULTS:**
Color panel is displayed in small size.

**EXPECTED RESULTS:**
Color panel should not display in small size.

 **SCREENSHOT:**
![a2](https://cloud.githubusercontent.com/assets/9950837/24740950/2139d302-1abd-11e7-98bd-5654f414ae03.png)

**Comment by k6Labz** [comment]
The issue still persist

**Comment by angieskazka** [comment]
looks fixed to me
