### ISSUE TITLE
When user switch between tabs,Countries name disappear and Bars color turn Black.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/gapminder-offline#82]
**SEVERITY:**  Major

**MODULE:** 
•	Bar Rank

**STEPS TO REPRODUCE:**
1.Open offline Application.
2.Open Bar rank in different tabs (4-5)
3.Switch between tabs.

**ACTUAL RESULTS:**
-Bar color turns black.
-Countries name disappear when user switch between tabs for second the time.
-Countries name display only in last tab(4th/5th) in black color. 

**EXPECTED RESULTS:**
-Bars should not turn Black.
-Countries name should be visible to user in all tabs after switching.

**SCREENSHOT:**
![a3](https://cloud.githubusercontent.com/assets/9950837/24742782/1ff3be56-1ac5-11e7-8369-5fb4bd5cd2e2.png)

![a4](https://cloud.githubusercontent.com/assets/9950837/24742800/27f87b14-1ac5-11e7-914c-81f90885ecc0.png)

![a5](https://cloud.githubusercontent.com/assets/9950837/24742805/2f001ade-1ac5-11e7-8cd2-4e6ff264571a.png)

![a6](https://cloud.githubusercontent.com/assets/9950837/24742818/4292dc30-1ac5-11e7-9256-609b4d50d261.png)

**Comment by Legionivo** [comment]
@kuguarpwnz countries name still disappear, steps are the same
