### ISSUE TITLE
Handle situation when too many tabs are opened

### ISSUE THREAD

**Issue by Legionivo** [Gapminder/gapminder-offline#85]
Steps to reproduce:
1. Open offline application.
2. Open many tabs so second row of tabs will appear

Actual result:
Play button and the whole bottom part of page is shifted down. Scroll appear on the right side.

Expected result: 
Window should be resized so all elements will be vizible.

![04_07_14 22 20_01](https://cloud.githubusercontent.com/assets/12167296/24801598/95bf814a-1bad-11e7-8d6d-3ae1baa45497.png)

**Comment by jheeffer** [comment]
@Legionivo I'm not sure if window resize is the right solution here. If you mean the whole application window. The application window should only resize when the user does it explicitly. 
Instead, if we're going to use multiple rows of tabs, the height of Vizabi should just be decreased I think?

**Comment by buchslava** [comment]
@jheeffer I think we should use logic like this: https://codepen.io/srees/pen/pgVLbm . I'm trying to provide it now.

**Comment by jheeffer** [comment]
Sure, that looks like an okay solution too : )! Great!
