### ISSUE TITLE
Source maps are not working

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#92]
i need source maps to be able to fix issues discovered in vizabi and charts
what i can see from debugger is only minified code 

![image](https://cloud.githubusercontent.com/assets/3648190/24964957/f184e5b2-1fa2-11e7-8b07-4fbdf4b523ad.png)

**Comment by buchslava** [comment]
@angieskazka we need to try this:

in `webpack.config.js`:

1. remove `devtool` key-value
2. add next block to `plugins section`:

```
    new webpack.SourceMapDevToolPlugin({
      filename: '[file].map'
    }),
```

more info here: https://github.com/webpack/webpack/issues/2145
