### ISSUE TITLE
test reading of DDF datasets [blocked by the lack of avail queries in vizabi]

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#98]
try out reading some ddf datasets: as a new chart or adding the data
to our experience it wasn't working =/

**Comment by Legionivo** [comment]
@angieskazka please provide more details

**Comment by angieskazka** [comment]
@Legionivo 
Press menu button in gapminder offline. chose new chart from DDF folder. Pick a folder that was previously downloaded/cloned on your computer. The app should show the data. 

I just tried and so far it crashes
